_wandb:
    value:
        cli_version: 0.23.1
        e:
            n4jc2whuapxymj6nguj9jpdlgt6vauv4:
                codePath: scripts\mlp_classifier_wandb
                codePathLocal: scripts\mlp_classifier_wandb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "126710968320"
                        used: "112597733376"
                email: gelilakassaye6@gmail.com
                executable: C:\Users\kewtiiiii\anaconda3\python.exe
                git:
                    commit: 6ec7da2a8b902f8618bb1319a65ef016566299ad
                    remote: https://github.com/GelilaK12/food-emissions-classification.git
                host: DESKTOP-1MKIQG9
                memory:
                    total: "7469842432"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\kewtiiiii\Desktop\Projects\food-emissions-classification\scripts\mlp_classifier_wandb
                python: CPython 3.13.5
                root: C:\Users\kewtiiiii\Desktop\Projects\food-emissions-classification
                startedAt: "2025-12-27T03:01:45.693050Z"
                writerId: n4jc2whuapxymj6nguj9jpdlgt6vauv4
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 3
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
mlp_activation:
    value: relu
mlp_alpha:
    value: 0.01
mlp_hidden_layers:
    value:
        - - 32
          - 16
mlp_max_iter:
    value: 1000
mlp_solver:
    value: adam
mlp_threshold:
    value: 0.4
