_wandb:
    value:
        cli_version: 0.23.1
        e:
            5i0v0bwzbq68vj68wqi9we6pq8algswy:
                codePath: scripts\wandb\xgboost_analysis_wandb
                codePathLocal: scripts\wandb\xgboost_analysis_wandb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "126710968320"
                        used: "112470769664"
                email: gelilakassaye6@gmail.com
                executable: C:\Users\kewtiiiii\anaconda3\python.exe
                git:
                    commit: 6ec7da2a8b902f8618bb1319a65ef016566299ad
                    remote: https://github.com/GelilaK12/food-emissions-classification.git
                host: DESKTOP-1MKIQG9
                memory:
                    total: "7469842432"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\kewtiiiii\Desktop\Projects\food-emissions-classification\scripts\wandb\xgboost_analysis_wandb
                python: CPython 3.13.5
                root: C:\Users\kewtiiiii\Desktop\Projects\food-emissions-classification
                startedAt: "2025-12-27T04:24:32.184877Z"
                writerId: 5i0v0bwzbq68vj68wqi9we6pq8algswy
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 3
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
xgb_learning_rate:
    value: 0.1
xgb_max_depth:
    value: 3
xgb_n_estimators:
    value: 100
